version: '3'
services:
    alkolicznik:
        image: 'icemajor/alkolicznik:latest'
        container_name: alkolicznik
        ports:
            - 443:8443
        depends_on:
            - psql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
            - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - GUI_DEFAULT_CITY=${GUI_DEFAULT_CITY}
            - MONEY_CURRENCY_UNIT=${MONEY_CURRENCY_UNIT}
            - JWT_KEY=${JWT_KEY}
            - IMAGEKIT_ID=${IMAGEKIT_ID}
            - IMAGEKIT_PUBLIC-KEY=${IMAGEKIT_PUBLIC_KEY}
            - IMAGEKIT_PRIVATE-KEY=${IMAGEKIT_PRIVATE_KEY}
    psql:
        image: 'postgres:alpine'
        ports:
            - 32:${DB_PORT}
        restart: always
        volumes:
            - psql-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
    psql-data:
        driver: local