version: '3'
services:
    alkolicznik:
        image: 'icemajor/alkolicznik:latest'
        command: --data.reload=${RELOAD} --data.delete=${DELETE}
        container_name: alkolicznik
        ports:
            - 443:8443
        depends_on:
            - psql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://psql:5432/alkolicznik
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=1111
            - GUI_DEFAULT-CITY=${GUI_DEFAULT_CITY}
            - GUI_COUNTRY=${GUI_COUNTRY}
            - MONEY_CURRENCY_UNIT=${MONEY_CURRENCY_UNIT}
            - JWT_KEY=${JWT_KEY}
            - IMAGEKIT_ID=${IMAGEKIT_ID}
            - IMAGEKIT_PUBLIC-KEY=${IMAGEKIT_PUBLIC_KEY}
            - IMAGEKIT_PRIVATE-KEY=${IMAGEKIT_PRIVATE_KEY}
            - IMAGEKIT_PATH=${IMAGEKIT_PATH}
    psql:
        image: 'postgres:alpine'
        ports:
            - 32:5432
        restart: always
        volumes:
            - psql-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=alkolicznik
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1111
volumes:
    psql-data:
        driver: local