version: '3'
services:
    alkolicznik:
        image: 'icemajor/alkolicznik:latest'
        container_name: alkolicznik
        ports:
          - 443:8443
        command: --spring.profiles.active=demo --spring.config.name=application,imageKit,jwt
        environment:
          - GUI_DEFAULT_CITY=${GUI_DEFAULT_CITY}
          - MONEY_CURRENCY_UNIT=${MONEY_CURRENCY_UNIT}
          - JWT_KEY=${JWT_KEY}
          - IMAGEKIT_ID=${IMAGEKIT_ID}
          - IMAGEKIT_PUBLIC-KEY=${IMAGEKIT_PUBLIC_KEY}
          - IMAGEKIT_PRIVATE-KEY=${IMAGEKIT_PRIVATE_KEY}