-- stores
INSERT INTO store (ID, NAME) VALUES (1, 'Carrefour')
ON CONFLICT DO NOTHING;
INSERT INTO store (ID, NAME) VALUES (2, 'Biedronka')
ON CONFLICT DO NOTHING;
INSERT INTO store (ID, NAME) VALUES (3, 'Grosik')
ON CONFLICT DO NOTHING;

-- beers
INSERT INTO beer (ID, NAME) VALUES (1, 'Perla')
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, NAME) VALUES (2, 'Ksiazece')
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, NAME) VALUES (3, 'Tyskie')
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, NAME) VALUES (4, 'Zubr')
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, NAME) VALUES (5, 'Komes')
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, NAME) VALUES (6, 'Miloslaw')
ON CONFLICT DO NOTHING;