-- stores
INSERT INTO store (ID, NAME) VALUES (1, 'Carrefour')
ON CONFLICT DO NOTHING;
INSERT INTO store (ID, NAME) VALUES (2, 'Biedronka')
ON CONFLICT DO NOTHING;
INSERT INTO store (ID, NAME) VALUES (3, 'Grosik')
ON CONFLICT DO NOTHING;

-- beers
INSERT INTO beer (ID, BRAND, TYPE, VOLUME) VALUES (1, 'Perla', 'Chmielowa Pils', 0.5)
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, BRAND, TYPE, VOLUME) VALUES (2, 'Ksiazece', 'Zlote pszeniczne', 0.5)
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, BRAND, TYPE, VOLUME) VALUES (3, 'Tyskie', 'Gronie', 0.6)
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, BRAND, VOLUME) VALUES (4, 'Zubr', 0.5)
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, BRAND, TYPE, VOLUME) VALUES (5, 'Komes', 'Malinowe', 0.33)
ON CONFLICT DO NOTHING;
INSERT INTO beer (ID, BRAND, TYPE, VOLUME) VALUES (6, 'Miloslaw', 'Biale', 0.5)
ON CONFLICT DO NOTHING;