DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS beers;

CREATE TABLE beers(
    id INTEGER IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL);

CREATE TABLE stores(
    id INTEGER IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    beer_id INTEGER FOREIGN KEY REFERENCES beers(id));